<?php
/* This file was generated by the metarefresh module at 2025-05-06T10:01:21Z
Do not update it manually as it will get overwritten
*/

$metadata['https://idm.clarin.eu'] = [
    'entityid' => 'https://idm.clarin.eu',
    'description' => [
        'en' => 'CLARIN ERIC',
    ],
    'OrganizationName' => [
        'en' => 'CLARIN ERIC',
    ],
    'name' => [
        'en' => 'clarin.eu website account',
    ],
    'OrganizationDisplayName' => [
        'en' => 'clarin.eu website account',
    ],
    'url' => [
        'en' => 'https://www.clarin.eu/',
    ],
    'OrganizationURL' => [
        'en' => 'https://www.clarin.eu/',
    ],
    'contacts' => [
        [
            'contactType' => 'technical',
            'givenName' => 'Dieter',
            'surName' => 'Van Uytvanck',
            'emailAddress' => [
                'spf@clarin.eu',
            ],
        ],
        [
            'contactType' => 'support',
            'givenName' => 'Dieter',
            'surName' => 'Van Uytvanck',
            'emailAddress' => [
                'spf@clarin.eu',
            ],
        ],
        [
            'contactType' => 'administrative',
            'givenName' => 'Dieter',
            'surName' => 'Van Uytvanck',
            'emailAddress' => [
                'spf@clarin.eu',
            ],
        ],
    ],
    'metadata-set' => 'saml20-idp-remote',
    'expire' => 1747387642,
    'SingleSignOnService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://idm.clarin.eu/saml-idp/saml2idp-web',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://idm.clarin.eu/saml-idp/saml2idp-web',
        ],
    ],
    'SingleLogoutService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://idm.clarin.eu/saml-idp/SLO-WEB',
            'ResponseLocation' => 'https://idm.clarin.eu:2443/unitygw/SAMLSLOResponseConsumer',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://idm.clarin.eu/saml-idp/SLO-WEB',
            'ResponseLocation' => 'https://idm.clarin.eu:2443/unitygw/SAMLSLOResponseConsumer',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP',
            'Location' => 'https://idm.clarin.eu/saml-idp/SLO-SOAP',
        ],
    ],
    'ArtifactResolutionService' => [],
    'NameIDFormats' => [
        'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
        'unity:userName',
        'urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName',
        'unity:persistent',
        'unity:identifier',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    ],
    'keys' => [
        [
            'encryption' => true,
            'signing' => true,
            'type' => 'X509Certificate',
            'X509Certificate' => 'MIIDazCCAlOgAwIBAgIEcg6/OjANBgkqhkiG9w0BAQsFADBmMQswCQYDVQQGEwJFVTEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEPMA0GA1UEChMGQ0xBUklOMQ0wCwYDVQQLEwRFUklDMRMwEQYDVQQDEwpDTEFSSU4gSURQMB4XDTE5MDcwMjEyNDgyMloXDTI5MDYyOTEyNDgyMlowZjELMAkGA1UEBhMCRVUxEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcTB1Vua25vd24xDzANBgNVBAoTBkNMQVJJTjENMAsGA1UECxMERVJJQzETMBEGA1UEAxMKQ0xBUklOIElEUDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALblZHdAAmUIavLjSKlrnekw3GKnC+TRcJZkyvULOfnJblgcMApkFwDpqE6uZACQXKmqR53Vua4brtrj4x5PQMJzkR6tIRvJctVpIwGtKzkSwllQz17XoG7au3RRrXA1VS0KKt3F3qn/OfO3qA3aitYzjCSmbb91EbUlbQ6wVcMM06Pk2gcszr3IWAHmxXLv5unuG2LFlllR1MUgFVaLi3b3m/z1QBCiTh/p0VTvqVulQKqcVZ24tlWO5FYMD7Akv9d41qamlThcBS8ZAbkJL8Xl1PbewFyQQv/jZ0BiLu8tpjJwHl8ER5SyGlMAL2O9Ut2ClHbU9UKFzwM7fK0FsNUCAwEAAaMhMB8wHQYDVR0OBBYEFBEcVjFsxe/VukQiNIpw8c9oUN8OMA0GCSqGSIb3DQEBCwUAA4IBAQAFYStP3jj8O141hIW9rJUVnCFQNEBUzTgo1qxpDTLqW1WiMFuVKMETXx884RNG0gvTyegH8BtIHhNEikGcaXblbe3rzfFd3NuutSz1I3PJ8smk59SFQEQ13rfbapvCwL6wFZm2zUa8OEKUPOdc2ez+My8MkUI+AG34pgDcYC0jIZY5FPhmbUMishxvECRk0/yIt3UOQ/8JJn1UpmMdwd7qZgJTGuAQnDtLb1rfwL7oBPOpErnSlI/wtv7zOuptY4J1u98lb7KNDqR3yU7t1QlbDfjoQmDAVD5HTF6Hqfjfn7ZcYvUnlFcGHmJNIVAES6WA/Q95ENpnoQ/v8WD9+BvT',
        ],
    ],
    'scope' => [
        'clarin.eu',
    ],
    'UIInfo' => [
        'DisplayName' => [
            'en' => 'clarin.eu website account',
        ],
        'Description' => [
            'en' => 'You can use this IdP when your academic account does not belong to an identity federation that has ties with the CLARIN Service Provider Federation. It is also known as the ‘homeless’ IdP.',
        ],
        'InformationURL' => [
            'en' => 'https://www.clarin.eu/content/clarin-identity-provider',
        ],
        'PrivacyStatementURL' => [],
        'Logo' => [
            [
                'url' => 'https://www.clarin.eu/sites/default/files/clarin-logo.png',
                'height' => 220,
                'width' => 195,
            ],
        ],
    ],
    'DiscoHints' => [
        'IPHint' => [],
        'DomainHint' => [
            'clarin.eu',
        ],
        'GeolocationHint' => [
            'geo:48.261811,11.673473',
        ],
    ],
    'tags' => [
        'clarin-idp',
    ],
    'metarefresh:src' => 'https://infra.clarin.eu/aai/prod_md_about_clarin_erics_idp.xml',
];
